### ISSUE TITLE
Popup Modal to Pause

### ISSUE THREAD

**Issue by mosdragon** [mosdragon/mule#19]
Hey @jpalusky could you find out how we can add a popup pause screen? Not only should it pause the timeline in **MasterController** but also give the option to save and quit your game. @sayemmh will work on getting some kind of file or map set up so when the user reopens the game, he/she sees the save date of the last few games saved.

**Comment by jpalusky** [comment]
Will do! I'm a bit slammed until wednesday, but I'll kick this out.

Sent from my T-Mobile 4G LTE Device-------- Original message --------From: Muhammad Osama Sakhi notifications@github.com Date: 10/25/2015  6:52 PM  (GMT-05:00) To: mosdragon/mule mule@noreply.github.com Cc: jpalusky josiahpalusky@gmail.com Subject: [mule] Popup Modal to Pause (#19) 
Hey @jpalusky could you find out how we can add a popup pause screen? Not only should it pause the timeline in MasterController but also give the option to save and quit your game. @sayemmh will work on getting some kind of file or map set up so when the user reopens the game, he/she sees the save date of the last few games saved.
