### ISSUE TITLE
Checkstyle/PMD

### ISSUE THREAD

**Issue by mosdragon** [mosdragon/mule#26]
Comment below with the files you will checkstyle/pmd. 

There are at least 40 files, so each person needs minimum 8. Please don't just snag all the easy ones. Do files from different directories so **(a)** we all know how the entire project comes together  and **(b)** we all end up checking code we didn't write so it's like real jobs where we code review each others' work:

Here is the directory tree:

```
.
├── MainApplication.java (X)
├── controller
│   ├── ConfigScreenController.java (X)
│   ├── GameMapController.java (X)
│   ├── MasterController.java (X)
│   ├── PlayerConfigController.java (X)
│   └── TownMapController.java (X)
├── model
│   ├── Constants.java (X)
│   ├── GameConfigs.java (X)
│   ├── GameDuration.java (X)
│   ├── GameSave.java (X)
│   ├── LocalGameSaves.java (X)
│   ├── MongoPersistence.java (X)
│   ├── Packable.java (X)
│   ├── Packer.java (X)
│   ├── Persistence.java
│   └── Store.java (X)
├── util
│   ├── Difficulty.java
│   ├── EnergyMule.java
│   ├── FoodMule.java
│   ├── GamePhase.java
│   ├── MapType.java
│   ├── Mule.java (X)
│   ├── MuleDeserializer.java (X)
│   ├── MuleFactory.java (X)
│   ├── MuleInterface.java
│   ├── OreMule.java
│   ├── Player.java (X)
│   ├── Property.java (X)
│   ├── PropertyType.java (X)
│   ├── Race.java (X)
│   ├── Resource.java (X)
│   ├── State.java (X)
│   └── Tile.java (X)
└── view
    ├── ConfigScreenView.java (X)
    ├── GameConfigView.java (X)
    ├── GameMapView.java (X)
    ├── LoadScreenView.java (X)
    ├── PauseScreenView.java (X)
    ├── PlayerConfigView.java (X)
    ├── PopupEventView.java (X)
    ├── ProductionView.java (X)
    └── TownMapView.java (X)

4 directories, 42 files
```

**Comment by mosdragon** [comment]
I'll take the following:

MainApplication

MasterController
TownMapController

GameSave
MongoPersistence
Persistence
Packer
Packable

MuleDeserializer
MuleFactory

**Comment by mosdragon** [comment]
@arihanshah @sayemmh @jpalusky @bruckw Checkstyle is tricky to set up.
1. Go to preferences/settings (for IntelliJ, not just settings for project), find plugins. Browse for plugins in the repository, and install CheckStyle-Idea. It's something like that. 
2. Restart IntelliJ, preferences -> other settings. You should see CheckStyle there, as well as a checkstyle frame at the bottom of the screen in IntelliJ where your debugger and terminal show.

There are **a lot** of checkstyle errors, many that are stupid things like "set x to a final class" so get on these asap, please and thank you

**Comment by bruckw** [comment]
I'll take these:
GameMapController

GameDuration
Store

Property
PropertyType
Tile
Resource

GameConfigView
GameMapView

**Comment by arihanshah** [comment]
I got these:

ConfigScreenController
GameConfigs
Player
Race
State
ConfigScreenView
PlayerConfigView
TownMapView

I also put this (X) on all the one's already taken to make it easier to pick.

**Comment by jpalusky** [comment]
I'll take these:

PlayerConfigController
Constants
LocalGameSaves
Mule
LoadScreenView
PauseScreenView
PopupEventView
ProductionView

I put Xs next to these too.
